apiVersion: apps/v1
kind: Deployment
metadata:
  name: kickboard
  labels:
    app: kickboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kickboard
  template:
    metadata:
      labels:
        app: kickboard
    spec:
      containers:
        - name: kickboard
          image: username/kickboard:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5